function Line2() {
  return (
    <symbol id="line2SvgContainer">
      <line
        x1={1420}
        y1={310}
        x2={720}
        y2={310}
        strokeWidth="8"
        stroke="#3DB44B"
      />
      <path
        d="M720,310 C583,310 583,430 583,430"
        fill="none"
        stroke="#3DB44B"
        strokeWidth="8"
      />
      <path
        d="M1420,310 C1540,310 1540,430 1540,430"
        fill="none"
        stroke="#3DB44B"
        strokeWidth="8"
      />
      <line
        x1={1548}
        y1={430}
        x2={1548}
        y2={250}
        strokeWidth="8"
        stroke="#3DB44B"
      />
      <line
        x1={1490}
        y1={190}
        x2={1370}
        y2={190}
        strokeWidth="8"
        stroke="#3DB44B"
      />
      <path
        d="M1548,250 C1548,190 1490,190 1490,190"
        fill="none"
        stroke="#3DB44B"
        strokeWidth="8"
      />
      <line
        x1={583}
        y1={865}
        x2={583}
        y2={430}
        strokeWidth="8"
        stroke="#3DB44B"
      />
      <path
        d="M583,865 C583,865 583,985 720,985"
        fill="none"
        stroke="#3DB44B"
        strokeWidth="8"
      />
      <line
        x1={720}
        y1={985}
        x2={1420}
        y2={985}
        strokeWidth="8"
        stroke="#3DB44B"
      />
      <path
        d="M1420,985 C1540,985 1540,865 1540,865"
        fill="none"
        stroke="#3DB44B"
        strokeWidth="8"
      />
      <line
        x1={1540}
        y1={865}
        x2={1540}
        y2={430}
        strokeWidth="8"
        stroke="#3DB44B"
      />
      <line
        x1={583}
        y1={820}
        x2={370}
        y2={820}
        strokeWidth="8"
        stroke="#3DB44B"
      />
      <path
        d="M370,820 C280,820 280,700 280,700"
        fill="none"
        stroke="#3DB44B"
        strokeWidth="8"
      />
      {/* station */}
      {/* 신정네거리 */}
      <circle
        cx={340}
        cy={815}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 양천구청 */}
      <circle
        cx={420}
        cy={820}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 도림천 */}
      <circle
        cx={490}
        cy={820}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 신도림 */}
      <rect
        width={15}
        height={40}
        x={576}
        y={800}
        rx={8}
        ry={8}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 문래 */}
      <circle
        cx={583}
        cy={760}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 합정 */}
      <rect
        width={15}
        height={30}
        x={576}
        y={500}
        rx={8}
        ry={8}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 당산 */}
      <rect
        width={15}
        height={30}
        x={576}
        y={590}
        rx={8}
        ry={8}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 홍대입구 */}
      <rect
        width={40}
        height={15}
        x={576}
        y={420}
        rx={8}
        ry={8}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 신촌 */}
      <circle
        cx={600}
        cy={370}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 이대 */}
      <circle
        cx={650}
        cy={325}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 아현 */}
      <circle
        cx={720}
        cy={310}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 시청 */}
      <rect
        width={15}
        height={30}
        x={840}
        y={290}
        rx={8}
        ry={8}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 을지로 입구 */}
      <circle
        cx={880}
        cy={310}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 을지로 3가 */}
      <rect
        width={15}
        height={30}
        x={905}
        y={300}
        rx={8}
        ry={8}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 신당 */}
      <rect
        width={15}
        height={30}
        x={1190}
        y={290}
        rx={8}
        ry={8}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 상왕십리 */}
      <circle
        cx={1290}
        cy={310}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 한양대 */}
      <circle
        cx={1480}
        cy={324}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 뚝섬 */}
      <circle
        cx={1527}
        cy={375}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 성수 */}
      <rect
        width={30}
        height={15}
        x={1530}
        y={420}
        rx={8}
        ry={8}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 용답 */}
      <circle
        cx={1548}
        cy={340}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 신답 */}
      <circle
        cx={1548}
        cy={250}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 용두 */}
      <circle
        cx={1440}
        cy={190}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 신설동 */}
      <rect
        width={15}
        height={40}
        x={1370}
        y={170}
        rx={8}
        ry={8}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 건대입구 */}
      <rect
        width={30}
        height={15}
        x={1530}
        y={480}
        rx={8}
        ry={8}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 구의 */}
      <circle
        cx={1540}
        cy={540}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 강변 */}
      <circle
        cx={1540}
        cy={600}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 잠실나루 */}
      <circle
        cx={1540}
        cy={720}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 잠실 */}
      <rect
        width={30}
        height={15}
        x={1530}
        y={810}
        rx={8}
        ry={8}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 잠실새내봉은사 */}
      <circle
        cx={1540}
        cy={865}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 종합운동장 */}
      <rect
        width={30}
        height={15}
        x={1505}
        y={910}
        rx={8}
        ry={8}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 삼성 */}
      <circle
        cx={1483}
        cy={970}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 선릉 */}
      <rect
        width={15}
        height={30}
        x={1410}
        y={975}
        rx={8}
        ry={8}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 역삼 */}
      <circle
        cx={1330}
        cy={985}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 강남 */}
      <rect
        width={15}
        height={30}
        x={1230}
        y={975}
        rx={8}
        ry={8}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 교대 */}
      <rect
        width={15}
        height={30}
        x={1130}
        y={975}
        rx={8}
        ry={8}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 서초 */}
      <circle
        cx={1080}
        cy={985}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 방배 */}
      <circle
        cx={1030}
        cy={985}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 낙성대 */}
      <circle
        cx={915}
        cy={985}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 서울대입구 */}
      <circle
        cx={855}
        cy={985}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 봉천 */}
      <circle
        cx={795}
        cy={985}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 신림 */}
      <circle
        cx={735}
        cy={985}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 신대방 */}
      <circle
        cx={670}
        cy={980}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 구로 디지털단지 */}
      <circle
        cx={620}
        cy={950}
        r={5}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* 대림 */}
      <rect
        width={30}
        height={15}
        x={580}
        y={890}
        rx={8}
        ry={8}
        fill="white"
        strokeWidth={5}
        stroke="#3DB44B"
      />
      {/* station name */}
      <text
        x={340}
        y={815}
        dx={-10}
        dy={-45}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        신정
        <tspan dx={-40} dy={30}>
          네거리
        </tspan>
      </text>
      <text
        x={420}
        y={820}
        dx={-20}
        dy={-45}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        양천
        <tspan dx={-40} dy={30}>
          구청
        </tspan>
      </text>
      <text
        x={490}
        y={820}
        dx={-30}
        dy={-15}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        도림천
      </text>
      <text
        x={576}
        y={820}
        dx={20}
        dy={7}
        fill="black"
        fontSize={20}
        fontWeight={800}
      >
        신도림
      </text>
      <text
        x={583}
        y={760}
        dx={15}
        dy={7}
        fill="black"
        fontSize={20}
        fontWeight={800}
      >
        문래
      </text>
      <text
        x={583}
        y={500}
        dx={15}
        dy={15}
        fill="black"
        fontSize={20}
        fontWeight={800}
      >
        합정
      </text>
      <text
        x={583}
        y={590}
        dx={15}
        dy={15}
        fill="black"
        fontSize={20}
        fontWeight={800}
      >
        당산
      </text>
      <text
        x={583}
        y={420}
        dx={40}
        dy={15}
        fill="black"
        fontSize={20}
        fontWeight={800}
      >
        홍대입구
      </text>
      <text
        x={600}
        y={370}
        dx={5}
        dy={20}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        신촌
      </text>
      <text
        x={650}
        y={325}
        dx={-5}
        dy={25}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        이대
      </text>
      <text
        x={720}
        y={315}
        dx={-20}
        dy={25}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        아현
      </text>
      <text
        x={840}
        y={290}
        dx={18}
        dy={10}
        fill="black"
        fontSize={20}
        fontWeight={800}
      >
        시청
      </text>
      <text
        x={880}
        y={310}
        dx={-58}
        dy={35}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        을지로
        <tspan dx={-45} dy={25}>
          입구
        </tspan>
      </text>
      <text
        x={880}
        y={310}
        dx={8}
        dy={45}
        fill="black"
        fontSize={20}
        fontWeight={800}
      >
        을지로
        <tspan dx={-45} dy={21}>
          3가
        </tspan>
      </text>
      <text
        x={1190}
        y={290}
        dx={20}
        dy={5}
        fill="black"
        fontSize={20}
        fontWeight={800}
      >
        신당
      </text>
      <text
        x={1290}
        y={310}
        dx={-30}
        dy={-15}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        상왕십리
      </text>
      <text
        x={1480}
        y={324}
        dx={-60}
        dy={30}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        한양대
      </text>
      <text
        x={1527}
        y={375}
        dx={-50}
        dy={15}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        뚝섬
      </text>
      <text
        x={1530}
        y={420}
        dx={40}
        dy={15}
        fill="black"
        fontSize={20}
        fontWeight={800}
      >
        성수
      </text>
      <text
        x={1548}
        y={340}
        dx={10}
        dy={15}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        용답
      </text>
      <text
        x={1548}
        y={250}
        dx={10}
        dy={8}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        신답
      </text>
      <text
        x={1440}
        y={190}
        dx={-20}
        dy={30}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        용두
      </text>
      <text
        x={1370}
        y={170}
        dx={20}
        dy={5}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        신설동
      </text>
      <text
        x={1530}
        y={470}
        dx={40}
        dy={25}
        fill="black"
        fontSize={20}
        fontWeight={800}
      >
        건대입구
      </text>
      <text
        x={1540}
        y={540}
        dx={15}
        dy={8}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        구의
      </text>
      <text
        x={1540}
        y={600}
        dx={15}
        dy={8}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        강변
      </text>
      <text
        x={1540}
        y={720}
        dx={15}
        dy={8}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        잠실나루
      </text>
      <text
        x={1555}
        y={810}
        dx={15}
        dy={15}
        fill="black"
        fontSize={20}
        fontWeight={800}
      >
        잠실
      </text>
      <text
        x={1540}
        y={865}
        dx={15}
        dy={8}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        잠실새내
      </text>
      <text
        x={1505}
        y={910}
        dx={40}
        dy={15}
        fill="black"
        fontSize={20}
        fontWeight={800}
      >
        종합운동장
      </text>
      <text
        x={1483}
        y={970}
        dx={5}
        dy={25}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        삼성
      </text>
      <text
        x={1410}
        y={975}
        dx={20}
        dy={40}
        fill="black"
        fontSize={20}
        fontWeight={800}
      >
        선릉
      </text>
      <text
        x={1330}
        y={985}
        dx={-20}
        dy={-15}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        역삼
      </text>
      <text
        x={1230}
        y={975}
        dx={-12}
        dy={-10}
        fill="black"
        fontSize={20}
        fontWeight={800}
      >
        강남
      </text>
      <text
        x={1130}
        y={975}
        dx={-10}
        dy={-10}
        fill="black"
        fontSize={20}
        fontWeight={800}
      >
        교대
      </text>
      <text
        x={1080}
        y={985}
        dx={-20}
        dy={-15}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        서초
      </text>
      <text
        x={1030}
        y={985}
        dx={-20}
        dy={-15}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        방배
      </text>
      <text
        x={915}
        y={985}
        dx={-26}
        dy={-15}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        낙성대
      </text>
      <text
        x={840}
        y={985}
        dx={-30}
        dy={35}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        서울대입구
      </text>
      <text
        x={795}
        y={985}
        dx={-20}
        dy={-15}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        봉천
      </text>
      <text
        x={737}
        y={985}
        dx={-20}
        dy={-15}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        신림
      </text>
      <text
        x={670}
        y={985}
        dx={-30}
        dy={30}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        신대방
      </text>
      <text
        x={525}
        y={950}
        dx={0}
        dy={25}
        fill="gray"
        fontSize={20}
        fontWeight={800}
      >
        구로
        <tspan dx={-85} dy={20}>
          디지털단지
        </tspan>
      </text>
      <text
        x={600}
        y={900}
        dx={15}
        dy={4}
        fill="black"
        fontSize={20}
        fontWeight={800}
      >
        대림
      </text>
    </symbol>
  );
}

export default Line2;
